### ISSUE TITLE
Report of a redacting issue on 4th project

### ISSUE THREAD

**Issue by Namelss4** [juanferfranco/SimulacionInteractivos#2]
On the 4th unit tab, right at the beggining, after the title "Proyecto 1" it says:

"No olvides que tu **una** aplicación interactiva en Ingeniería en Diseño de Entretenimiento Digital se queda **corra** si deja de contar una historia, si no hay narrativa."

![image](https://github.com/juanferfranco/SimulacionInteractivos/assets/82066453/c99e89bb-e436-48fb-8992-5768667b8e3a)

That sentence has some clear issues, I guess the original developer meant:

"No olvides que tu aplicación interactiva en Ingeniería en Diseño de Entretenimiento Digital se queda corta si deja de contar una historia, si no hay narrativa."

**Comment by juanferfranco** [comment]
Thank you Jero for your helping to improve the course material.
